USE abirvalarg_tk;
CREATE TABLE user (
	id			INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	login		CHAR(32) NOT NULL UNIQUE,
	password	CHAR(60) NOT NULL,
	isActive	SET('N', 'Y') NOT NULL DEFAULT 'Y',
	isAdmin		SET('N', 'Y') NOT NULL DEFAULT 'N',
	dispName	VARCHAR(255) NULL DEFAULT NULL
) ENGINE InnoDB;
